title: <p align="center"> Abhishekh Shah </p>
logo: /assets/img/logo.jpeg

description:
  <br>   
  I'm worked on various Embedded domians like, IoT, Aerospace, Medical.
  Skilled in programming scripting (C, C++, Python), Lauterbach scripting, knowledge of Standard DO 178B and working ability in Agile base projects.
  I have 6.8yrs of total experience.
  <br>
  </p>



theme: jekyll-theme-minimal
