title: Shah Abhishekh Pareshkumar
logo: /assets/img/logo.jpeg
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/abhishekh-shah/">LinkedIn</a> |
  <a href="https://github.com/abhi-alone">GitHub</a>

  <br>   
Experienced Engineer with a demonstrated history of working in the Embedded technology and services industry. Skilled in programming scripting (C, C++, Python), Lauterbach scripting, knowledge of Standard DO 178B and working ability in Agile base projects. Strong engineering professional graduated from the University of Pune. .
  <br>
  </p>
theme: jekyll-theme-minimal
